from torchsegmentor.operator.distributed_operator import DistributedOperator
from torchsegmentor.operator.pspnet_operator import PSPNetOperator
from torchsegmentor.operator.deeplabv3plus_operator import DeeplabV3PlusOperator
#from torchsegmentor.operator.kenet_operator import KENetOperator
#from torchsegmentor.operator.highwaynet_operator import HighwayNetOperator